services:
  postgres:
    image: postgres:15
    container_name: dev_ecommerce_db
    environment:
      POSTGRES_USER: devUser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: dev_ecommerce_db

    ports:
      - "5433:5432"

    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./dev_ecommerce_db.backup:/docker-entrypoint-initdb.d/dev_ecommerce_db.backup