services:
  postgres:
    image: postgres:17
    container_name: dev_ecommerce_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "${DB_PORT}:5432"

    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./dev_ecommerce_db.backup:/docker-entrypoint-initdb.d/dev_ecommerce_db.backup